language: node_js

notifications:
  email: false

cache:
  yarn: true

node_js:
  - '7'
  - '6'

services:
  - mongodb

before_install:
 - yarn upgrade

script:
  - npm test

after_success:
  # - git config --global user.email "builds@travis-ci.com"
  # - git config --global user.name "Travis CI"
  # - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  # - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  # - git push -q https://$TAGPERM@github.com/andreasonny83/carcassonne-scoreboard-server --tags
  # - ls -R
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/andreasonny83/arcassonne-scoreboard-server $GIT_TAG > /dev/null 2>&1

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - master
